[colors.bright]
black = "#555555"
blue = "#92baff"
cyan = "#a0bfdf"
green = "#88cf88"
magenta = "#e0b2d6"
red = "#ffa0a0"
white = "#ffffff"
yellow = "#d2b580"

[colors.cursor]
background = "#777777"
text = "#000000"

[colors.dim]
black = "#222222"
blue = "#00a2ff"
cyan = "#30ffc0"
green = "#00fc50"
magenta = "#ff8bd4"
red = "#fb6859"
white = "#dddddd"
yellow = "#ffdd00"

[colors.normal]
black = "#000000"
blue = "#29aeff"
cyan = "#00d3d0"
green = "#00fc50"
magenta = "#feacd0"
red = "#ff8059"
white = "#eeeeee"
yellow = "#eecc00"

[colors.primary]
background = "#292a30"
foreground = "#ffffff"
